### ISSUE TITLE
errors with WinPython

### ISSUE THREAD

**Issue by AlexLee** [nick-parker/python3Dplay#1]
Nick,

I imported scipy using Winpython. I am running main.py in the "Shift method" folder. When running, your slicer I get these errors. 

Traceback (most recent call last):
  File "C:\Users\z003EE9Y\Desktop\WinPython-32bit-2.7.9.2\slicer\main.py", line 10, in <module>
    test = stl_importer.stl_import("model.stl")
  File "C:\Users\z003EE9Y\Desktop\WinPython-32bit-2.7.9.2\slicer\stl_importer.py", line 44, in stl_import
    output=mesh.mesh(currentTris)
  File "C:\Users\z003EE9Y\Desktop\WinPython-32bit-2.7.9.2\slicer\mesh.py", line 18, in **init**
    self.updateLims()
  File "C:\Users\z003EE9Y\Desktop\WinPython-32bit-2.7.9.2\slicer\mesh.py", line 28, in updateLims
    self.region[0][0]=[[max(Xs),max(Ys),max(Zs)],[min(Xs),min(Ys),min(Zs)]]
ValueError: setting an array element with a sequence.

Error 1 test = stl_importer.stl_import("model.stl")

Error 2 output=mesh.mesh(currentTris)

Error 3    self.updateLims()

Error 4         self.region[0][0]=[[max(Xs),max(Ys),max(Zs)],[min(Xs),min(Ys),min(Zs)]]

**Comment by nick-parker** [comment]
The issue you have is most likely caused by a binary .stl file - the importer only works with ASCII formatting. If that's not the case, I have no idea what it's doing.

That said, I haven't touched this code base in the better part of a year - to make it actually do nonplanar slicing you'll need to solve an unsolved problem in 3d graphics. The working slicer I assume you saw on my Google+ is in a private git, and won't be public until i figure some other stuff out.

**Comment by AlexLee** [comment]
thanks, Nick. You write brilliant code and I appreciate you sharing your knowledge with the open source community.

I was referring to this python slicer that you wrote over a year ago not the private git one. I'll try it with an ASCII format. 

Has topolabs solved the nonplanar slicing problem or have they just come up with a workaround?

**Comment by nick-parker** [comment]
I don't have any non-public knowledge on what Topolabs is up to. 

Though to be clear, I've solved nonplanar slicing with a different approach. The unsolved problem I referred to in my previous comment is tesselating a mesh based on an arbitrary 2D triangle grid so that the mesh can be warped along that grid. It's necessary for this approach, but not for the broader problem.
